### ISSUE TITLE
`open': No such file or directory - -w (Errno::ENOENT)

### ISSUE THREAD

**Issue by 128keaton** [dmathieu/glynn#58]
Sorry, another issue. I can connect fine with the settings, but it refuses to do anything related to uploading. I've tried multiple directory settings.

_config.yml:
```
markdown: discount
highlighter: pigments

ftp_host: 'ftp.128keaton.com'
ftp_dir: '/more/beta/'

ftp_passive: false

# optional
ftp_port: 21                  # default 21
ftp_username: ''     # default read from stdin
ftp_password: '' # default read from stdin
ftp_secure: false            # default false

```

The home directory of the user I am using has their path set properly. 

Full error:
```
Sending site over FTP (host: ftp.128keaton.com, port: 21, ftps: false)
Connected to server. Sending site
/Library/Ruby/Gems/2.0.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:46:in `open': No such file or directory - -w (Errno::ENOENT)
	from /Library/Ruby/Gems/2.0.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:46:in `foreach'
	from /Library/Ruby/Gems/2.0.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:46:in `send_dir'
	from /Library/Ruby/Gems/2.0.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:17:in `block in sync'
	from /Library/Ruby/Gems/2.0.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:27:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:135:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:23:in `connect'
	from /Library/Ruby/Gems/2.0.0/gems/glynn-1.2.3/lib/glynn/ftp.rb:16:in `sync'
	from /Library/Ruby/Gems/2.0.0/gems/glynn-1.2.3/bin/glynn:80:in `<top (required)>'
	from /usr/local/bin/glynn:23:in `load'
	from /usr/local/bin/glynn:23:in `<main>'
```

**Comment by 128keaton** [comment]
-w breaks everything

**Comment by dmathieu** [comment]
I see you've closed the issue. Is your problem resolved?

**Comment by 128keaton** [comment]
@dmathieu yeah, I was trying to do --watch
